// _data/cities.js â€” City page data for Sunflower Plumbing
// Each city gets a tailored page with local context, streets, and history.

module.exports = [
  {
    slug: 'andover',
    name: 'Andover',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing provides expert plumbing and septic services to Andover, KS. Licensed, local, and available 24/7. Call (316) 333-6326.',
    heroSub: 'Fast, reliable plumbing and septic services for Andover homes and businesses.',
    intro: 'Andover is one of Butler County\'s fastest-growing communities, and its newer subdivisions along Andover Road and 21st Street bring a mix of modern construction and the plumbing surprises that come with it. Whether you\'re in a newer development near Andover Central Park or an older neighborhood closer to US-54, Sunflower Plumbing is the team locals call when something goes wrong.',
    localDetail: 'We\'ve worked throughout Andover â€” from homes near Meadowlark Road to commercial properties along Rock Road. After the tornadoes of 1991 and 2022, Andover rebuilt with thousands of new homes. That new construction is now aging into its first round of water heater replacements, drain issues, and pipe repairs. We\'re here for all of it.',
    callout: 'Serving Andover neighborhoods including Wheatland Estates, the Andover Road corridor, and the growing communities near 21st Street.',
  },
  {
    slug: 'augusta',
    name: 'Augusta',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing serves Augusta, KS with expert plumbing, septic, and excavation services. Locally owned, 24/7 emergency response. Call (316) 333-6326.',
    heroSub: 'Trusted plumbing and septic services for Augusta homes and businesses.',
    intro: 'Augusta is Butler County\'s second-largest city, with deep roots in the Kansas oil industry and a tight-knit community that expects quality work. Sunflower Plumbing has been a familiar name on State Street, Dearborn Street, and throughout Augusta\'s residential neighborhoods â€” delivering honest plumbing and septic service with no runaround.',
    localDetail: 'From the older homes near downtown Augusta and the Augusta Municipal Airport corridor to the newer developments east of Rock Road, we\'ve handled plumbing systems of every age and condition. Augusta\'s mix of vintage homes and newer builds means we see everything from cast iron pipes to modern PEX â€” and we know how to handle both.',
    callout: 'Serving Augusta neighborhoods including downtown Augusta, the State Street corridor, and residential areas near Bornholdt Park.',
  },
  {
    slug: 'bel-aire',
    name: 'Bel Aire',
    county: 'Sedgwick County',
    metaDesc: 'Sunflower Plumbing provides plumbing and septic services to Bel Aire, KS. Licensed, insured, transparent pricing. Call (316) 333-6326.',
    heroSub: 'Professional plumbing services for Bel Aire homes â€” fast, honest, and upfront.',
    intro: 'Bel Aire sits just north of Wichita and has grown steadily into a community of well-kept homes and local businesses along Woodlawn and 53rd Street North. Sunflower Plumbing extends its service area to Bel Aire homeowners who want the same transparent pricing and reliable work we deliver throughout Butler County.',
    localDetail: 'Many Bel Aire homes were built in the 1970s through 1990s and are entering the decades where water heaters, supply lines, and drain systems need attention. We diagnose honestly, quote upfront, and fix it right â€” without the guesswork.',
    callout: 'Serving Bel Aire neighborhoods along Woodlawn Boulevard, 53rd Street North, and the surrounding residential areas.',
  },
  {
    slug: 'benton',
    name: 'Benton',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing serves Benton, KS and surrounding Butler County with plumbing, septic, and excavation services. Call (316) 333-6326.',
    heroSub: 'Local plumbing and septic service for Benton and rural Butler County.',
    intro: 'Benton is a quiet Butler County community where many properties rely on private wells, septic systems, and rural plumbing setups that demand a knowledgeable local team. Sunflower Plumbing understands rural Kansas systems inside and out â€” from septic inspections to well-water line repairs.',
    localDetail: 'Rural properties around Benton often have aging septic systems and plumbing that hasn\'t been touched in decades. We come prepared, diagnose thoroughly, and only recommend what\'s actually needed. No upselling, no surprises.',
    callout: 'Serving Benton and surrounding rural Butler County properties with septic, plumbing, and excavation services.',
  },
  {
    slug: 'burns',
    name: 'Burns',
    county: 'Marion County',
    metaDesc: 'Sunflower Plumbing provides plumbing and septic services to Burns, KS and surrounding Marion County communities. Call (316) 333-6326.',
    heroSub: 'Honest plumbing and septic service for Burns and surrounding rural Kansas.',
    intro: 'Burns is a small Marion County community where neighbors still know each other and expect service people to show up when they say they will. Sunflower Plumbing brings that same small-town accountability to every job â€” transparent pricing, prompt response, and work done right.',
    localDetail: 'Rural properties in the Burns area often depend on septic systems and private water sources. We\'re experienced in rural plumbing diagnostics and can handle everything from septic repairs to full lateral field installations.',
    callout: 'Serving Burns and the surrounding rural Marion and Butler County communities.',
  },
  {
    slug: 'cassoday',
    name: 'Cassoday',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing serves Cassoday, KS with expert plumbing and septic services. Call (316) 333-6326.',
    heroSub: 'Plumbing and septic service for Cassoday and the open range of eastern Butler County.',
    intro: 'Cassoday â€” known as the Prairie Chicken Capital of the World â€” sits on the edge of the Flint Hills where rural properties spread across open grassland. Sunflower Plumbing regularly services properties in and around Cassoday, handling the unique plumbing and septic needs of rural Flint Hills homesteads.',
    localDetail: 'Properties in the Cassoday area often have older septic systems and rely on well water. We\'re experienced with rural setups, perform honest inspections, and can handle septic repairs, lateral field work, and plumbing service for homes and ranch properties alike.',
    callout: 'Serving Cassoday and surrounding eastern Butler County ranch and rural properties.',
  },
  {
    slug: 'derby',
    name: 'Derby',
    county: 'Sedgwick County',
    metaDesc: 'Sunflower Plumbing provides expert plumbing and septic services to Derby, KS. Fast response, upfront pricing, 24/7 emergency service. Call (316) 333-6326.',
    heroSub: 'Professional plumbing services for Derby homes and businesses â€” day or night.',
    intro: 'Derby is one of the fastest-growing cities in Kansas, with neighborhoods expanding along Rock Road, Madison Avenue, and south toward Mulvane. Sunflower Plumbing serves Derby homeowners and businesses with honest, no-surprise service â€” transparent quotes, licensed work, and 24/7 emergency availability.',
    localDetail: 'Derby\'s rapid growth means a wide range of home ages â€” from classic mid-century ranches near downtown to brand-new construction subdivisions east of Rock Road. We\'ve worked throughout Derby and know what each era of construction brings when it comes to plumbing.',
    callout: 'Serving Derby neighborhoods including those along Rock Road, Madison Avenue, and the growing communities near US-15.',
  },
  {
    slug: 'eastborough',
    name: 'Eastborough',
    county: 'Sedgwick County',
    metaDesc: 'Sunflower Plumbing provides professional plumbing services to Eastborough, KS. Licensed, insured, upfront pricing. Call (316) 333-6326.',
    heroSub: 'Discreet, professional plumbing service for Eastborough\'s established homes.',
    intro: 'Eastborough is one of Kansas\'s most distinctive small cities â€” an enclave community within east Wichita known for its well-maintained estates and quiet residential streets. Sunflower Plumbing brings professional, tidy workmanship to Eastborough homes, respecting both the property and the homeowner\'s time.',
    localDetail: 'Many Eastborough homes were built in the mid-20th century and feature older plumbing systems that benefit from regular inspection. We work carefully, clean up after ourselves, and handle every job with the professionalism these properties deserve.',
    callout: 'Serving Eastborough\'s established residential neighborhoods near Woodlawn and Kellogg.',
  },
  {
    slug: 'el-dorado',
    name: 'El Dorado',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing is El Dorado\'s trusted plumbing and septic company. Locally owned, licensed, and available 24/7. Call (316) 333-6326.',
    heroSub: 'El Dorado\'s hometown plumbing and septic team â€” locally owned, locally trusted.',
    intro: 'El Dorado is home. Sunflower Plumbing is based right here on West Central Avenue, and we\'ve been serving the Butler County seat with reliable plumbing and septic service from day one. Whether you\'re near El Dorado State Park, the downtown historic district, or out on the west side near US-77, we\'re your neighbors â€” not a call center franchise.',
    localDetail: 'El Dorado was built on oil money and has the character to prove it â€” from the historic homes near 8th Avenue and Emporia Street to the newer developments west of Main Street. We know this city\'s plumbing quirks, its older cast iron systems, and the issues that come with Kansas weather. We\'re your team for everything from dripping faucets to septic emergencies.',
    callout: 'Proudly serving all of El Dorado including downtown, West Central, the hospital district, and rural properties surrounding the city.',
  },
  {
    slug: 'eureka',
    name: 'Eureka',
    county: 'Greenwood County',
    metaDesc: 'Sunflower Plumbing provides plumbing and septic services to Eureka, KS and surrounding Greenwood County. Call (316) 333-6326.',
    heroSub: 'Honest plumbing and septic service for Eureka and surrounding Greenwood County.',
    intro: 'Eureka is the county seat of Greenwood County â€” a small Kansas city with a strong community spirit and older housing stock that needs experienced hands. Sunflower Plumbing travels to Eureka for plumbing repairs, septic work, and excavation projects, bringing Butler County expertise to the neighboring county.',
    localDetail: 'Older homes in Eureka often have aging galvanized pipes, outdated water heaters, and septic systems that predate modern design standards. We assess honestly and fix only what needs fixing â€” no unnecessary upsells.',
    callout: 'Serving Eureka and surrounding Greenwood County communities for plumbing and septic needs.',
  },
  {
    slug: 'haysville',
    name: 'Haysville',
    county: 'Sedgwick County',
    metaDesc: 'Sunflower Plumbing serves Haysville, KS with expert plumbing, drain cleaning, and septic services. Fast response, fair pricing. Call (316) 333-6326.',
    heroSub: 'Dependable plumbing services for Haysville homes and businesses.',
    intro: 'Haysville sits just south of Wichita along US-81 and has a strong sense of community that expects reliable, honest service. Sunflower Plumbing serves Haysville homeowners with upfront pricing and professional workmanship on all plumbing and septic work.',
    localDetail: 'From neighborhoods near Grand Street and Main to the residential streets east of Rock Road, we\'ve handled Haysville plumbing jobs of all sizes. Older homes in south Haysville often have cast iron drain lines that need camera inspection before any work begins â€” we do it right.',
    callout: 'Serving Haysville neighborhoods along US-81, Main Street, and throughout south Sedgwick County.',
  },
  {
    slug: 'leon',
    name: 'Leon',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing serves Leon, KS and rural Butler County with plumbing, septic, and excavation services. Call (316) 333-6326.',
    heroSub: 'Local plumbing and septic service for Leon and rural southwest Butler County.',
    intro: 'Leon is a small Butler County community surrounded by farmland and rural properties that depend on reliable plumbing and working septic systems. Sunflower Plumbing serves Leon and the surrounding area with honest, experienced service â€” no runaround, no inflated prices.',
    localDetail: 'Rural properties near Leon often have older systems that need careful diagnosis. We\'re experienced with private wells, older septic tanks, and the excavation work that comes with rural property plumbing. We\'ll tell you exactly what\'s needed and why.',
    callout: 'Serving Leon and the surrounding rural Butler County communities with plumbing, septic, and excavation services.',
  },
  {
    slug: 'mulvane',
    name: 'Mulvane',
    county: 'Sedgwick County',
    metaDesc: 'Sunflower Plumbing provides plumbing and septic services to Mulvane, KS. Licensed, insured, available 24/7. Call (316) 333-6326.',
    heroSub: 'Professional plumbing services for Mulvane homes and businesses.',
    intro: 'Mulvane sits at the crossroads of Sedgwick and Sumner counties, with a growing population and a mix of older and newer homes along Main Street and Rock Road. Sunflower Plumbing serves Mulvane with fast response times and transparent pricing on all plumbing and septic work.',
    localDetail: 'From older homes near downtown Mulvane to newer subdivisions on the city\'s edges, we\'ve worked across the full range of Mulvane\'s housing stock. We\'re familiar with the drain and sewer challenges that come with southern Sedgwick County soil conditions.',
    callout: 'Serving Mulvane including neighborhoods along Main Street, Rock Road, and the US-81 corridor.',
  },
  {
    slug: 'newton',
    name: 'Newton',
    county: 'Harvey County',
    metaDesc: 'Sunflower Plumbing serves Newton, KS with professional plumbing, water heater, and drain services. Upfront pricing, fast response. Call (316) 333-6326.',
    heroSub: 'Reliable plumbing services for Newton, Kansas â€” fast, honest, and local.',
    intro: 'Newton is Harvey County\'s county seat and a city with a rich railroad history along Main Street and Broadway. Sunflower Plumbing extends its service area to Newton, bringing Butler County reliability to Harvey County homeowners who want an honest plumber without the franchise runaround.',
    localDetail: 'Many Newton homes date to the late 19th and early 20th century, when this was a railroad boomtown. That older housing stock often features galvanized pipes, cast iron drains, and original fixtures that require experienced hands. We assess carefully and repair or replace based on what makes sense for your home â€” not what generates the biggest invoice.',
    callout: 'Serving Newton and surrounding Harvey County with plumbing and water heater services.',
  },
  {
    slug: 'park-city',
    name: 'Park City',
    county: 'Sedgwick County',
    metaDesc: 'Sunflower Plumbing provides plumbing and drain services to Park City, KS. Fast response, transparent pricing. Call (316) 333-6326.',
    heroSub: 'Professional plumbing service for Park City homes and businesses.',
    intro: 'Park City is a growing Sedgwick County community north of Wichita along I-135, with a mix of residential neighborhoods and commercial development. Sunflower Plumbing serves Park City homeowners and businesses with reliable, upfront service throughout the area.',
    localDetail: 'Park City homes along the I-135 corridor span a wide age range — from mid-century builds near Hydraulic Avenue to newer construction north of 61st Street. Older Park City properties frequently have galvanized supply lines and original water heaters that have been patched rather than replaced. We diagnose honestly and quote upfront before any work begins.',
    callout: 'Serving Park City neighborhoods along Hydraulic Avenue, 61st Street North, and the I-135 corridor.',
  },
  {
    slug: 'peabody',
    name: 'Peabody',
    county: 'Marion County',
    metaDesc: 'Sunflower Plumbing serves Peabody, KS with plumbing and septic services. Licensed and insured. Call (316) 333-6326.',
    heroSub: 'Local plumbing and septic service for Peabody and Marion County.',
    intro: 'Peabody is a quiet Marion County community with strong roots in Kansas agricultural history. Sunflower Plumbing serves Peabody homeowners and rural property owners who need honest, experienced plumbing and septic service without driving to the city.',
    localDetail: 'Rural properties around Peabody rely heavily on private wells and aging septic systems — many installed when these Marion County farmsteads were first developed in the mid-20th century. We inspect thoroughly, give you an honest assessment of what\'s actually needed, and won\'t recommend work your system doesn\'t require.',
    callout: 'Serving Peabody and surrounding Marion County communities for plumbing and septic service.',
  },
  {
    slug: 'potwin',
    name: 'Potwin',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing provides plumbing and septic services to Potwin, KS and surrounding Butler County. Call (316) 333-6326.',
    heroSub: 'Honest plumbing and septic service for Potwin and rural Butler County.',
    intro: 'Potwin is a small Butler County town where people expect straightforward service and honest prices. Sunflower Plumbing serves Potwin and surrounding rural properties with the same no-surprise approach we bring to every job across Butler County.',
    localDetail: 'Rural Butler County properties around Potwin depend heavily on private septic systems and well-sourced plumbing — many on land that hasn\'t had a professional inspection in years. We come prepared for older systems, assess the full picture before recommending any work, and handle both plumbing and excavation in-house without subcontracting.',
    callout: 'Serving Potwin and surrounding rural Butler County with plumbing, septic, and well-related services.',
  },
  {
    slug: 'rose-hill',
    name: 'Rose Hill',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing serves Rose Hill, KS with expert plumbing, septic, and drain services. Licensed, insured, local. Call (316) 333-6326.',
    heroSub: 'Dependable plumbing services for Rose Hill\'s homes and growing community.',
    intro: 'Rose Hill is a Butler County community southeast of Wichita that has seen steady residential growth in recent years. With newer subdivisions going up alongside established neighborhoods, Rose Hill homeowners deal with the full spectrum of plumbing needs â€” from new construction to aging infrastructure in older homes.',
    localDetail: 'We\'ve worked throughout Rose Hill on both residential and light commercial jobs. Newer construction east of Rose Hill Road often needs water heater installations and fixture work, while older sections closer to downtown may see drain and sewer issues from aging cast iron.',
    callout: 'Serving Rose Hill neighborhoods including the Rose Hill Road corridor and surrounding eastern Butler County communities.',
  },
  {
    slug: 'rosalia',
    name: 'Rosalia',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing serves Rosalia, KS and rural Butler County with plumbing and septic services. Call (316) 333-6326.',
    heroSub: 'Local plumbing and septic service for Rosalia and rural southeast Butler County.',
    intro: 'Rosalia is a small rural community in southeastern Butler County, where properties often rely on private water and septic systems. Sunflower Plumbing serves Rosalia and surrounding rural properties with experienced, honest service â€” no inflated prices, no unnecessary work.',
    localDetail: 'Rural properties around Rosalia in southeastern Butler County are frequently on private septic systems and well water — some of the most isolated service calls in our coverage area. We come prepared with the right equipment, give you an honest assessment of what the system actually needs, and handle both the plumbing and any required excavation in-house.',
    callout: 'Serving Rosalia and the surrounding rural southeastern Butler County area.',
  },
  {
    slug: 'towanda',
    name: 'Towanda',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing provides plumbing and septic services to Towanda, KS. Locally owned, licensed, upfront pricing. Call (316) 333-6326.',
    heroSub: 'Reliable plumbing and septic service for Towanda and northern Butler County.',
    intro: 'Towanda is a quiet Butler County community north of El Dorado along the Whitewater River. Many properties here have private septic systems and older plumbing that benefits from a knowledgeable local team. Sunflower Plumbing is based right in Butler County and brings that local expertise to every Towanda job.',
    localDetail: 'Towanda\'s mix of rural properties and established residential neighborhoods means we handle everything from septic pumping and repairs to in-home drain cleaning and fixture replacement. We\'re close by and ready.',
    callout: 'Serving Towanda and surrounding northern Butler County communities including rural properties along the Whitewater River corridor.',
  },
  {
    slug: 'valley-center',
    name: 'Valley Center',
    county: 'Sedgwick County',
    metaDesc: 'Sunflower Plumbing serves Valley Center, KS with expert plumbing and septic services. Fast response, fair pricing. Call (316) 333-6326.',
    heroSub: 'Professional plumbing services for Valley Center homes and businesses.',
    intro: 'Valley Center sits north of Wichita along the Arkansas River and has grown into a community where both long-time residents and new families expect reliable local service. Sunflower Plumbing serves Valley Center with fast response and transparent pricing on all plumbing and septic work.',
    localDetail: 'Valley Center homes range from older farmhouses along the river corridor to newer residential developments. We\'re experienced with the full range and bring the same honest assessment to every job â€” no matter the age or condition of the system.',
    callout: 'Serving Valley Center neighborhoods along Main Street, the Arkansas River corridor, and surrounding north Sedgwick County communities.',
  },
  {
    slug: 'whitewater',
    name: 'Whitewater',
    county: 'Butler County',
    metaDesc: 'Sunflower Plumbing serves Whitewater, KS and surrounding Butler County with plumbing and septic services. Call (316) 333-6326.',
    heroSub: 'Honest plumbing and septic service for Whitewater and northern Butler County.',
    intro: 'Whitewater is a Butler County community along the Whitewater River with a strong agricultural heritage and a mix of rural and residential properties. Sunflower Plumbing serves Whitewater with transparent, no-surprise service that Butler County has come to expect.',
    localDetail: 'Properties along the Whitewater River corridor depend on private septic systems and well water. The river corridor also elevates soil moisture in some areas, which accelerates lateral field degradation and pipe corrosion over time. Many Whitewater-area homes were built in the 1970s and 80s, putting them squarely in range for water heater replacement, drain line repairs, and septic system service. We handle all of it in-house.',
    callout: 'Serving Whitewater and surrounding northern Butler County rural communities.',
  },
  {
    slug: 'wichita',
    name: 'Wichita',
    county: 'Sedgwick County',
    metaDesc: 'Sunflower Plumbing provides plumbing, drain, and septic services to Wichita, KS. Licensed, insured, available 24/7. Call (316) 333-6326.',
    heroSub: 'Expert plumbing services for Wichita homes and businesses â€” available 24/7.',
    intro: 'Wichita is Kansas\'s largest city and a community that demands professional service, fast response, and honest pricing. Sunflower Plumbing serves Wichita and the greater metro with the same Butler County values â€” transparent quotes before any work begins, licensed and insured technicians, and 24/7 emergency availability.',
    localDetail: 'From historic homes in College Hill and the Riverside neighborhood to post-war ranches in the southwest and new construction near K-96, Wichita\'s diverse housing stock covers every era of plumbing. We\'ve worked across the city on jobs ranging from simple faucet repairs to full sewer line replacements. Whatever the issue, we diagnose it right the first time.',
    callout: 'Serving Wichita neighborhoods including College Hill, Riverside, Delano, East Side, and communities throughout the metro area.',
  },
  {
    slug: 'winfield',
    name: 'Winfield',
    county: 'Cowley County',
    metaDesc: 'Sunflower Plumbing serves Winfield, KS with professional plumbing and septic services. Upfront pricing, fast response. Call (316) 333-6326.',
    heroSub: 'Dependable plumbing services for Winfield and Cowley County.',
    intro: 'Winfield is the county seat of Cowley County and home to Southwestern College â€” a community that combines small-city character with active local businesses and established neighborhoods. Sunflower Plumbing extends its service area to Winfield for homeowners and businesses that want honest, professional plumbing work.',
    localDetail: 'Winfield\'s older neighborhoods near Main Street and Manning Street feature homes built in the late 19th and early 20th century, with plumbing systems that often need careful assessment before any repair work begins. We inspect thoroughly and give you an honest quote before touching anything.',
    callout: 'Serving Winfield and surrounding Cowley County communities for plumbing, drain, and water heater services.',
  },
];



