// _data/services.js — Service config for service+location page generation
// Each entry maps to a sub-service page and drives the 456 service+location pages.

module.exports = [
  {
    slug: 'plumbing',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Plumbing Services',
    shortName: 'Plumbing',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing',          // /plumbing/el-dorado-ks/
    isTopLevel: true,
    tagline: 'Licensed plumbing for homes and businesses',
    pitch: 'Full-service plumbing — from leaky faucets to full pipe replacements. Licensed, insured, and locally owned in Butler County.',
    serviceBody: 'Sunflower Plumbing handles the full range of residential and commercial plumbing needs. Whether you need a faucet replaced, a water line repaired, or a full re-pipe on an older home, we diagnose honestly, quote upfront, and fix it right.',
    differentiator: 'One licensed plumber covers the full scope — no trade handoffs, no inflated subcontractor markups.',
    urgencyNote: 'Plumbing issues that go unaddressed almost always get worse. We offer 24/7 emergency response for urgent situations.',
    cta: 'Call for a plumbing quote',
  },
  {
    slug: 'water-heater-repair',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Water Heater Repair & Installation',
    shortName: 'Water Heater Repair',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/water-heater-repair',
    isTopLevel: false,
    tagline: 'Water heater repair and replacement',
    pitch: 'Water heater repair and installation in {{CITY_NAME}}, KS. Same-day service on most calls. Tank and tankless units.',
    serviceBody: 'When your water heater fails in {{CITY_NAME}}, you need a local plumber who can respond fast. Sunflower Plumbing handles water heater repairs, element replacements, thermostat repairs, and full unit replacements — both tank and tankless. We carry common parts and units on the truck, so most jobs are handled same-day.',
    differentiator: 'We\'ll tell you honestly whether your unit needs a repair or a replacement — not just what generates the bigger ticket.',
    urgencyNote: 'A failing water heater often gives warning signs: discolored water, popping or rumbling sounds, or inconsistent temperature. Don\'t wait for a full failure.',
    cta: 'Call for water heater service',
  },
  {
    slug: 'drain-cleaning',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Drain Cleaning & Clog Removal',
    shortName: 'Drain Cleaning',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/drain-cleaning',
    isTopLevel: false,
    tagline: 'Drain cleaning and clog removal',
    pitch: 'Drain cleaning and clog removal in {{CITY_NAME}}, KS. Kitchen drains, bathroom drains, main line clogs — we clear them all.',
    serviceBody: 'A slow or stopped drain in {{CITY_NAME}} is more than an inconvenience — it can signal a deeper issue in the drain line. Sunflower Plumbing clears kitchen drains, bathroom drains, floor drains, and main sewer lines using professional hydro-jetting and drain snake equipment. We also camera inspect when a recurring clog suggests a structural problem in the line.',
    differentiator: 'We don\'t just clear the clog and leave. If a camera shows root intrusion, grease buildup, or pipe damage, we tell you what\'s causing it — not just treat the symptom.',
    urgencyNote: 'A completely stopped drain — especially on the main line — needs same-day attention. We\'re available 24/7 for drain emergencies.',
    cta: 'Call for drain service',
  },
  {
    slug: 'leak-detection',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Leak Detection & Repair',
    shortName: 'Leak Detection',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/leak-detection',
    isTopLevel: false,
    tagline: 'Leak detection and pipe repair',
    pitch: 'Leak detection and pipe repair in {{CITY_NAME}}, KS. Visible and hidden leaks found fast — before they become water damage.',
    serviceBody: 'Hidden leaks in {{CITY_NAME}} homes can run water bills up hundreds of dollars a month and cause structural damage before you see a wet spot. Sunflower Plumbing locates hidden leaks in walls, under slabs, and in supply lines using professional detection equipment — then repairs what we find cleanly and correctly.',
    differentiator: 'We locate the leak before we open the wall. No unnecessary demolition, no guesswork.',
    urgencyNote: 'If your water bill spiked unexpectedly or you hear running water when nothing is on, call us before a hidden leak causes serious damage.',
    cta: 'Call for leak detection',
  },
  {
    slug: 'toilet-faucet-repair',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Toilet & Faucet Repair',
    shortName: 'Toilet & Faucet Repair',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/toilet-faucet-repair',
    isTopLevel: false,
    tagline: 'Toilet and faucet repair',
    pitch: 'Toilet and faucet repair in {{CITY_NAME}}, KS. Running toilets, dripping faucets, flush valve failures — fixed right.',
    serviceBody: 'Running toilets and dripping faucets in {{CITY_NAME}} are more than annoyances — a running toilet can waste 200 gallons a day. Sunflower Plumbing repairs fill valves, flappers, flush valves, and faucet cartridges, and handles toilet and faucet replacements when repair isn\'t the right call. We stock common parts and handle most repairs in a single visit.',
    differentiator: 'No parts-run delays on most common repairs — we carry the hardware to fix it the first time.',
    urgencyNote: 'A toilet that won\'t stop running or a faucet dripping overnight adds up fast on your water bill. Usually a quick fix when caught early.',
    cta: 'Call for toilet or faucet repair',
  },
  {
    slug: 'fixture-replacement',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Fixture Replacement & Installation',
    shortName: 'Fixture Replacement',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/fixture-replacement',
    isTopLevel: false,
    tagline: 'Fixture replacement and installation',
    pitch: 'Fixture replacement and installation in {{CITY_NAME}}, KS. Sinks, toilets, showers, tubs — supply-and-install or install-only.',
    serviceBody: 'Updating fixtures in your {{CITY_NAME}} home — or replacing worn-out originals — is a straightforward job when you have the right plumber. Sunflower Plumbing handles sink, toilet, shower, and tub fixture replacements for both residential and light commercial properties. We can supply the fixture or install customer-supplied units.',
    differentiator: 'Install-only option available if you\'ve already selected your fixtures — we connect it correctly and make sure it doesn\'t leak.',
    urgencyNote: 'Fixture upgrades often go smoother when the supply valves are in good shape first. We check them at installation — no surprises after the new fixture goes in.',
    cta: 'Call to schedule fixture installation',
  },
  {
    slug: 'gas-line-services',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Gas Line Services',
    shortName: 'Gas Line Services',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/gas-line-services',
    isTopLevel: false,
    tagline: 'Gas line repair and installation',
    pitch: 'Gas line repair and installation in {{CITY_NAME}}, KS. Licensed gas piping work — appliance connections, new lines, leak detection.',
    serviceBody: 'Gas line work in {{CITY_NAME}} requires a licensed plumber — and it\'s not a job to delay if you smell gas or suspect a leak. Sunflower Plumbing handles gas line repairs, new gas line runs for appliances and generators, and gas leak detection. If you smell gas, leave the building and call 911 before calling us.',
    differentiator: 'We hold the plumbing license required for gas piping work in Kansas — no unlicensed workarounds.',
    urgencyNote: 'If you smell sulfur or rotten eggs anywhere in your home, leave immediately and call 911. Gas leaks are emergencies.',
    cta: 'Call for gas line service',
  },
  {
    slug: 'kitchen-bathroom-plumbing',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Kitchen & Bathroom Plumbing',
    shortName: 'Kitchen & Bathroom Plumbing',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/kitchen-bathroom-plumbing',
    isTopLevel: false,
    tagline: 'Kitchen and bathroom plumbing',
    pitch: 'Kitchen and bathroom plumbing in {{CITY_NAME}}, KS. Remodels, repairs, fixture installs, and rough-in for new construction.',
    serviceBody: 'Kitchen and bathroom plumbing in {{CITY_NAME}} covers everything from a remodel rough-in to a single fixture repair. Sunflower Plumbing handles supply line and drain work for kitchen remodels, bathroom renovations, and new additions — as well as repairs on existing systems. We coordinate with your contractor or work directly with homeowners on self-managed projects.',
    differentiator: 'We do both rough-in and finish plumbing — no need to coordinate two separate plumbers at different project phases.',
    urgencyNote: 'Remodel timelines depend on plumbing. Book early — kitchen and bathroom rough-in slots fill up faster than most homeowners expect.',
    cta: 'Call to schedule kitchen or bathroom plumbing',
  },
  {
    slug: 'water-softener-installation',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Water Softener Installation',
    shortName: 'Water Softener Installation',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/water-softener-installation',
    isTopLevel: false,
    tagline: 'Water softener installation and service',
    pitch: 'Water softener installation in {{CITY_NAME}}, KS. Hard water solutions for Butler County homes — professional installation, no DIY guesswork.',
    serviceBody: 'Hard water is a real issue in {{CITY_NAME}} and throughout Kansas. Scale buildup damages water heaters, shortens appliance life, and leaves spots on everything it touches. Sunflower Plumbing installs water softeners and filtration systems with proper bypass valve configuration, drain connections, and startup testing — so the system actually works when we leave.',
    differentiator: 'Proper bypass valve installation and drain line configuration — details that get skipped on DIY and big-box installs.',
    urgencyNote: 'Hard water in Kansas shortens water heater life significantly. A water softener installation often pays for itself in reduced appliance wear.',
    cta: 'Call to schedule water softener installation',
  },
  {
    slug: 'sewer-line-repair',
    parentHub: 'plumbing',
    hubSlug: 'plumbing',
    displayName: 'Sewer Line Repair & Replacement',
    shortName: 'Sewer Line Repair',
    hubLabel: 'Plumbing',
    schemaType: 'Plumber',
    urlPrefix: 'plumbing/sewer-line-repair',
    isTopLevel: false,
    tagline: 'Sewer line repair and replacement',
    pitch: 'Sewer line repair and replacement in {{CITY_NAME}}, KS. Camera inspection, targeted repair, or full replacement — handled in-house.',
    serviceBody: 'Sewer line problems in {{CITY_NAME}} show up as slow drains, sewage backup, or unexplained wet spots in the yard. Sunflower Plumbing camera inspects the line to find the exact failure point — root intrusion, pipe collapse, joint separation — then repairs or replaces only what\'s necessary. We handle the excavation in-house, so there\'s no split scope between contractors.',
    differentiator: 'Camera inspection first. We find the problem before opening the ground — no exploratory digging.',
    urgencyNote: 'Sewage backup into the home is a health hazard. If multiple fixtures are backing up simultaneously, call us immediately — this is an emergency.',
    cta: 'Call for sewer line service',
  },
  {
    slug: 'septic-services',
    parentHub: 'septic',
    hubSlug: 'septic',
    displayName: 'Septic Services',
    shortName: 'Septic Services',
    hubLabel: 'Septic',
    schemaType: 'LocalBusiness',
    urlPrefix: 'septic',
    isTopLevel: true,
    tagline: 'Full-service septic care',
    pitch: 'Septic services in {{CITY_NAME}}, KS. Inspection, repair, and system maintenance for rural and residential properties.',
    serviceBody: 'Septic systems on {{CITY_NAME}} properties need regular attention to function correctly — and when they fail, they fail badly. Sunflower Plumbing handles septic inspections, tank pumping coordination, distribution box repairs, and full system replacements. We also handle the excavation in-house, so septic work doesn\'t require two contractors.',
    differentiator: 'We handle both the plumbing connections and the excavation — one contractor, full scope, one point of accountability.',
    urgencyNote: 'A septic system showing signs of failure — slow drains throughout the house, sewage smell near the tank or field, wet ground over the lateral field — needs attention before it becomes a full backup.',
    cta: 'Call for septic service',
  },
  {
    slug: 'lateral-field-installation',
    parentHub: 'septic',
    hubSlug: 'septic',
    displayName: 'Lateral Field Installation',
    shortName: 'Lateral Field Installation',
    hubLabel: 'Septic',
    schemaType: 'LocalBusiness',
    urlPrefix: 'septic/lateral-field-installation',
    isTopLevel: false,
    tagline: 'Septic lateral field installation and replacement',
    pitch: 'Lateral field installation and replacement in {{CITY_NAME}}, KS. Permitted, inspected, and built to KDHE spec.',
    serviceBody: 'Lateral field replacement in {{CITY_NAME}} is a full excavation and permitting project — not something to patch or delay. Sunflower Plumbing designs, permits, excavates, and installs lateral fields to KDHE specifications and Butler County requirements. We handle the full scope from soil assessment through final inspection.',
    differentiator: 'Full scope in-house: system design, permit coordination, excavation, installation, and inspection. No subcontractor coordination.',
    urgencyNote: 'A saturated lateral field won\'t recover on its own. If the ground over your field is wet or sewage is surfacing, you need a field assessment now.',
    cta: 'Call for lateral field assessment',
  },
  {
    slug: 'excavation',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Excavation Services',
    shortName: 'Excavation',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation',
    isTopLevel: true,
    tagline: 'Licensed excavation contractor',
    pitch: 'Excavation services in {{CITY_NAME}}, KS. Utility trenching, septic excavation, site prep — licensed plumber on every job.',
    serviceBody: 'Sunflower Plumbing\'s excavation services in {{CITY_NAME}} cover the full range of residential and commercial excavation needs — from utility trenching and septic system work to site preparation and foundation backfill. As a licensed plumber who also operates excavation equipment, we handle jobs that require both in a single scope without subcontractor coordination.',
    differentiator: 'Licensed plumber operating the excavation equipment — the only contractor who can legally do the dig and the pipe connections on the same job.',
    urgencyNote: 'Excavation emergencies — collapsed lines, surfacing sewage — require immediate response. We\'re available 24/7.',
    cta: 'Call for excavation service',
  },
  {
    slug: 'sewer-water-line-excavation',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Sewer & Water Line Excavation',
    shortName: 'Sewer & Water Line Excavation',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/sewer-water-line-excavation',
    isTopLevel: false,
    tagline: 'Sewer and water line excavation',
    pitch: 'Sewer and water line excavation in {{CITY_NAME}}, KS. One contractor handles the dig and the pipe connections — no split scope.',
    serviceBody: 'Sewer and water line excavation in {{CITY_NAME}} requires both heavy equipment and a plumbing license — and Sunflower Plumbing brings both. We excavate, repair or replace the line, and backfill and compact — all in-house. No waiting on a second contractor to connect what the excavator opened.',
    differentiator: 'We call 811 before every dig. In {{COUNTY_NAME}}\'s older neighborhoods, as-built utility records are often inaccurate — we proceed carefully even after marking.',
    urgencyNote: 'A broken water main or collapsed sewer is an emergency. We respond 24/7.',
    cta: 'Call for sewer or water line excavation',
  },
  {
    slug: 'septic-system-excavation',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Septic System Excavation',
    shortName: 'Septic System Excavation',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/septic-system-excavation',
    isTopLevel: false,
    tagline: 'Septic tank and field excavation',
    pitch: 'Septic system excavation in {{CITY_NAME}}, KS. Tank installs, field excavation, and full system replacement — permitted and inspected.',
    serviceBody: 'Septic system excavation in {{CITY_NAME}} involves careful coordination of soil conditions, KDHE permit requirements, and proper tank and field placement. Sunflower Plumbing handles the full scope — tank excavation, bed and set, lateral field trenching, distribution box installation, and final inspection — without splitting the job between a plumber and a separate excavator.',
    differentiator: 'One contractor for the full system. We hold the plumbing license and operate the equipment — no coordination gap between trades.',
    urgencyNote: 'Septic failures need immediate attention. Surfacing sewage is a health code violation and an environmental hazard — don\'t wait.',
    cta: 'Call for septic excavation',
  },
  {
    slug: 'trenching',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Trenching Services',
    shortName: 'Trenching',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/trenching',
    isTopLevel: false,
    tagline: 'Utility and drainage trenching',
    pitch: 'Trenching services in {{CITY_NAME}}, KS. Utility lines, septic laterals, drainage, and outbuilding runs — 811 marked, properly backfilled.',
    serviceBody: '{{COUNTY_NAME}}\'s clay-dominant soils require proper trenching technique — the right equipment, correct depth, and compacted backfill to prevent settling that can damage buried lines over time. Sunflower Plumbing handles utility trenching, septic lateral field trenching, French drain installation, and outbuilding utility runs throughout {{CITY_NAME}} and surrounding areas.',
    differentiator: '811 called before every dig. Backfilled and compacted in lifts — we don\'t leave a settling trench that shifts your buried lines a year later.',
    urgencyNote: 'Kansas law requires 811 notification before any excavation. We handle the notification and wait for marking before starting.',
    cta: 'Call for trenching service',
  },
  {
    slug: 'site-preparation',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Site Preparation',
    shortName: 'Site Preparation',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/site-preparation',
    isTopLevel: false,
    tagline: 'Site prep and rough grading',
    pitch: 'Site preparation in {{CITY_NAME}}, KS. Land clearing, rough grading, and utility rough-in for new construction and additions.',
    serviceBody: 'Site preparation in {{CITY_NAME}} requires attention to drainage grading — particularly with {{COUNTY_NAME}}\'s clay soils, which hold water and can undermine building pads when drainage isn\'t properly established. Sunflower Plumbing handles land clearing, rough grading, building pad excavation, and utility rough-in as a coordinated scope — so your builder arrives to a ready site.',
    differentiator: 'We coordinate utility rough-in with site grading — one mobilization covers both instead of scheduling two contractors separately.',
    urgencyNote: 'Remodel and new construction timelines are tight. Book site prep early — excavation slots fill ahead of foundation pours.',
    cta: 'Call for site preparation',
  },
  {
    slug: 'backfill-grading',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Backfill & Grading',
    shortName: 'Backfill & Grading',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/backfill-grading',
    isTopLevel: false,
    tagline: 'Foundation backfill and drainage grading',
    pitch: 'Backfill and grading in {{CITY_NAME}}, KS. Foundation backfill, drainage correction, and lot leveling — compacted to prevent settling.',
    serviceBody: 'Drainage problems on {{CITY_NAME}} properties frequently trace back to improperly compacted backfill or grading that slopes toward the foundation rather than away from it. {{COUNTY_NAME}}\'s clay soils make this worse — clay swells when wet and creates lateral pressure against foundation walls. Sunflower Plumbing grades to direct water away from structures and backfills in properly compacted lifts to prevent long-term settling.',
    differentiator: 'We grade with long-term drainage in mind — not just enough slope to pass an inspection on day one.',
    urgencyNote: 'Negative grade around a foundation gets worse every wet season. Correcting it early is significantly cheaper than addressing foundation damage later.',
    cta: 'Call for backfill or grading service',
  },
  {
    slug: 'emergency-excavation',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Emergency Excavation',
    shortName: 'Emergency Excavation',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/emergency-excavation',
    isTopLevel: false,
    tagline: '24/7 emergency excavation',
    pitch: 'Emergency excavation in {{CITY_NAME}}, KS. Collapsed lines, burst water mains, failed septic — 24/7 local response from El Dorado.',
    serviceBody: 'When a sewer line collapses or a water main bursts in {{CITY_NAME}}, you need a contractor who can respond immediately with both excavation equipment and a plumbing license. Sunflower Plumbing is based in El Dorado — not dispatching from Wichita — so response times throughout {{COUNTY_NAME}} are faster than most alternatives.',
    differentiator: 'Locally based crew with equipment. We\'re not routing from Wichita — faster response throughout {{COUNTY_NAME}}.',
    urgencyNote: 'Collapsed sewer lines, burst water mains, and surfacing septic systems are health and safety emergencies. Call us immediately at (316) 333-6326.',
    cta: 'Call now — 24/7 emergency response',
  },
];
