        a: 'Yes. We trench to the correct depth for each utility type and backfill correctly. Call us with the run length and what you are running — water line, electrical conduit, or communication cable — and we will give you a scope and price.',
      },
      {
        q: 'What is a French drain and can you install one in {{CITY_NAME}}?',
        a: 'A French drain is a gravel-filled trench with a perforated pipe that redirects groundwater away from a structure or wet area. We install French drains for basement drainage, foundation waterproofing, and yard drainage problems throughout {{COUNTY_NAME}}.',
      },
    ],
  },
  {
    slug: 'site-preparation',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Site Preparation',
    shortName: 'Site Preparation',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/site-preparation',
    isTopLevel: false,
    tagline: 'Site prep and rough grading',
    pitch: 'Site preparation in {{CITY_NAME}}, KS. Land clearing, rough grading, and utility rough-in for new construction and additions.',
    serviceBody: 'Site preparation in {{CITY_NAME}} requires attention to drainage grading — particularly with {{COUNTY_NAME}}\'s clay soils, which hold water and can undermine building pads when drainage is not properly established. Sunflower Plumbing handles land clearing, rough grading, building pad excavation, and utility rough-in as a coordinated scope — so your builder arrives to a ready site.\n\nFor new construction in {{COUNTY_NAME}}, the site preparation sequence matters. Utility rough-in — sewer, water, and gas stub-outs — needs to happen before the building pad is graded and compacted. Running utilities after pad prep means cutting back into compacted soil, which adds time and cost. We coordinate the sequencing so utilities are in the right place before grade is established.\n\nDrainage grading in clay soils requires more attention than in sandy or loam areas. Clay does not absorb water quickly, so surface drainage has to move water away from the building footprint efficiently. Poor drainage around a foundation shows up as wet basements, foundation wall pressure, and long-term structural issues. We grade with long-term drainage performance in mind, not just enough slope to pass the initial inspection.\n\nFor lot preparation on rural {{CITY_NAME}} properties, we handle tree and brush clearing, topsoil stripping, rough grading, and access road establishment — everything needed to get a site ready for foundation work.',
    differentiator: 'We coordinate utility rough-in with site grading — one mobilization covers both instead of scheduling two contractors separately.',
    urgencyNote: 'Remodel and new construction timelines are tight. Book site prep early — excavation slots in {{CITY_NAME}} fill ahead of foundation pours.',
    cta: 'Call for site preparation',
    faqs: [
      {
        q: 'When should site preparation happen in the construction sequence?',
        a: 'Site prep — including utility rough-in, rough grading, and building pad establishment — needs to happen before foundation work starts. Utility stubs should be in place before the pad is compacted. We coordinate the sequencing so nothing needs to be cut back into after grade is set.',
      },
      {
        q: 'Do you handle tree and brush clearing in {{CITY_NAME}}?',
        a: 'Yes. We handle clearing, topsoil stripping, rough grading, and access establishment as part of site preparation. For heavily wooded lots, we can provide a scope after a site visit.',
      },
      {
        q: 'Why does drainage grading matter more in {{COUNTY_NAME}} clay soils?',
        a: 'Clay absorbs water slowly. If the grade around a building does not move surface water away efficiently, it pools against the foundation — creating hydrostatic pressure, wet basements, and long-term structural problems. We grade for long-term drainage performance, not just initial slope.',
      },
      {
        q: 'Can you handle site prep for an addition to an existing home?',
        a: 'Yes. Additions often require utility extensions — sewer, water, gas, and electrical conduit rough-in — coordinated with the foundation excavation. We handle the excavation and utility rough-in so your foundation contractor arrives to a ready site.',
      },
      {
        q: 'How long does site preparation take for a new construction project in {{CITY_NAME}}?',
        a: 'It depends on lot size, clearing requirements, and utility run lengths. A straightforward residential lot typically takes 1-2 days for rough grading and utility rough-in. We will give you a timeline estimate after reviewing the site or plans.',
      },
    ],
  },
  {
    slug: 'backfill-grading',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Backfill & Grading',
    shortName: 'Backfill & Grading',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/backfill-grading',
    isTopLevel: false,
    tagline: 'Foundation backfill and drainage grading',
    pitch: 'Backfill and grading in {{CITY_NAME}}, KS. Foundation backfill, drainage correction, and lot leveling — compacted to prevent settling.',
    serviceBody: 'Drainage problems on {{CITY_NAME}} properties frequently trace back to improperly compacted backfill or grading that slopes toward the foundation rather than away from it. {{COUNTY_NAME}}\'s clay soils make this worse — clay swells when wet and creates lateral pressure against foundation walls. Sunflower Plumbing grades to direct water away from structures and backfills in properly compacted lifts to prevent long-term settling.\n\nFoundation backfill is one of the most commonly rushed steps in construction. The excavated material gets pushed back in quickly, without compaction, and within a few seasons the grade around the foundation has settled and water is running toward the building instead of away from it. Correcting negative grade after the fact is disruptive and expensive — doing it correctly at backfill is straightforward.\n\nFor drainage correction on established properties in {{CITY_NAME}}, we assess where water is pooling or running toward the structure and regrade to redirect it. This sometimes involves bringing in select fill material — not all native clay is suitable for backfill, particularly when it has been mixed with organic material from topsoil stripping.\n\nLot leveling for properties with uneven terrain or settled areas involves cutting high spots and filling low spots with compacted material. We bring the lot to a consistent grade that drains correctly and provides a stable surface for whatever comes next — lawn, landscaping, or pavement.',
    differentiator: 'We grade with long-term drainage in mind — not just enough slope to pass an inspection on day one.',
    urgencyNote: 'Negative grade around a foundation gets worse every wet season in {{CITY_NAME}}. Correcting it early is significantly cheaper than addressing foundation damage later.',
    cta: 'Call for backfill or grading service',
    faqs: [
      {
        q: 'What is negative grade and why is it a problem?',
        a: 'Negative grade means the ground slopes toward the foundation rather than away from it. Water running toward the foundation creates hydrostatic pressure against the wall, wet basements, and over time, structural damage. It is a common problem on homes where backfill was not properly compacted at construction.',
      },
      {
        q: 'How do you correct drainage problems around a foundation in {{CITY_NAME}}?',
        a: 'We regrade the area around the foundation to establish positive drainage — at least 6 inches of drop over the first 10 feet away from the structure. Sometimes this involves bringing in select fill material to build up low areas before regrading. We assess the situation before recommending a scope.',
      },
      {
        q: 'Does {{COUNTY_NAME}} clay soil cause extra problems for backfill?',
        a: 'Yes. Clay swells when wet and shrinks when dry, creating movement that can shift foundation walls and settle buried utilities. Proper backfill in clay soils means compacting in lifts — typically 6-8 inch lifts — using a compactor, not just pushing material back in with the bucket.',
      },
      {
        q: 'Can you level a lot or yard in {{CITY_NAME}} for drainage or aesthetic reasons?',
        a: 'Yes. Lot leveling involves cutting high spots, filling low spots with compacted material, and establishing a consistent grade that drains correctly. We handle both drainage-driven leveling and preparation for lawn or landscaping projects.',
      },
      {
        q: 'What kind of fill material do you use for backfill and grading?',
        a: 'We use compactable fill appropriate to the application — typically granular fill or select native material free from organic debris. We avoid using topsoil or material with high organic content for structural backfill, as organic material decomposes and causes settling over time.',
      },
    ],
  },
  {
    slug: 'emergency-excavation',
    parentHub: 'excavation',
    hubSlug: 'excavation',
    displayName: 'Emergency Excavation',
    shortName: 'Emergency Excavation',
    hubLabel: 'Excavation',
    schemaType: 'LocalBusiness',
    urlPrefix: 'excavation/emergency-excavation',
    isTopLevel: false,
    tagline: '24/7 emergency excavation',
    pitch: 'Emergency excavation in {{CITY_NAME}}, KS. Collapsed lines, burst water mains, failed septic — 24/7 local response from El Dorado.',
    serviceBody: 'When a sewer line collapses or a water main bursts in {{CITY_NAME}}, you need a contractor who can respond immediately with both excavation equipment and a plumbing license. Sunflower Plumbing is based in El Dorado — not dispatching from Wichita — so response times throughout {{COUNTY_NAME}} are faster than most alternatives.\n\nEmergency excavation situations share one characteristic: waiting makes them worse. A collapsed sewer line backs up into the home. A burst water main floods the yard and cuts water service. A failed septic system surfaces and creates a health code violation. These are not situations where you schedule for next week — they require same-day, often same-hour response.\n\nWe keep equipment available for emergency dispatch and respond 24/7 including weekends and holidays. On arrival, we assess the situation quickly — locate the failure, determine the scope of repair, and get to work. We hold a Kansas plumbing license, so we can make the pipe connections the same day the ground is opened. No waiting on a separate plumber after the excavation crew leaves.\n\nFor water main emergencies, we coordinate with your utility provider on shutoff and restore service as quickly as possible. For sewer emergencies, we get the backup resolved and restore normal drain function before closing the site.',
    differentiator: 'Locally based crew with equipment. We are not routing from Wichita — faster response throughout {{COUNTY_NAME}}.',
    urgencyNote: 'Collapsed sewer lines, burst water mains, and surfacing septic systems are health and safety emergencies. Call us immediately at (316) 333-6326.',
    cta: 'Call now — 24/7 emergency response',
    faqs: [
      {
        q: 'What counts as an excavation emergency?',
        a: 'Collapsed sewer lines causing backup into the home, burst water mains cutting service or flooding the property, surfacing septic systems creating health code violations, and any situation where a failed buried utility is causing active damage or health risk. Call us — we respond 24/7.',
      },
      {
        q: 'How fast can you respond to an emergency in {{CITY_NAME}}?',
        a: 'We are based in El Dorado and serve {{COUNTY_NAME}} directly — not routing from Wichita. Response times vary by current workload, but our local base means we are typically on-site faster than competitors who dispatch from the Wichita metro.',
      },
      {
        q: 'Do you respond to emergencies on weekends and holidays?',
        a: 'Yes — 24/7, 365 days a year. Plumbing and excavation emergencies do not respect business hours. Call (316) 333-6326 any time.',
      },
      {
        q: 'Can you fix the pipe the same day you excavate?',
        a: 'Yes. We hold a Kansas plumbing license, so we can make the pipe connections the same day the ground is opened. You do not wait for a second contractor after the excavation is done — we handle both.',
      },
      {
        q: 'What should I do while waiting for emergency excavation in {{CITY_NAME}}?',
        a: 'For a burst water main, locate and shut off the main water shutoff to the home if possible. For a sewer backup, stop using any drains, toilets, or water-consuming appliances. For a surfacing septic system, keep people and pets away from the affected area. Call us at (316) 333-6326 and we will talk you through it.',
      },
    ],
  },
];
